export const ACTIONS = {
    // Navigation
    MPCS_NAV_DASHBOARD: "MPCS_NAV_DASHBOARD",
    MPCS_NAV_PHONES: "MPCS_NAV_PHONES",
    MPCS_NAV_RULES: "MPCS_NAV_RULES",
    MPCS_NAV_TEMPLATES: "MPCS_NAV_TEMPLATES",
    MPCS_NAV_GENERATE: "MPCS_NAV_GENERATE",
    MPCS_NAV_PROJECTS: "MPCS_NAV_PROJECTS",
    MPCS_NAV_SETTINGS: "MPCS_NAV_SETTINGS",

    // Dashboard
    MPCS_DASHBOARD_ADD_PHONE: "MPCS_DASHBOARD_ADD_PHONE",
    MPCS_DASHBOARD_CREATE_TEMPLATE: "MPCS_DASHBOARD_CREATE_TEMPLATE",
    MPCS_DASHBOARD_GENERATE_PROJECT: "MPCS_DASHBOARD_GENERATE_PROJECT",

    // Phones
    MPCS_PHONES_ADD: "MPCS_PHONES_ADD",
    MPCS_PHONES_EDIT: "MPCS_PHONES_EDIT",
    MPCS_PHONES_DELETE: "MPCS_PHONES_DELETE",
    MPCS_PHONES_SAVE: "MPCS_PHONES_SAVE",
    MPCS_PHONES_SPEC_ADD_ROW: "MPCS_PHONES_SPEC_ADD_ROW",
    MPCS_PHONES_SPEC_REMOVE_ROW: "MPCS_PHONES_SPEC_REMOVE_ROW",

    // Rules
    MPCS_RULES_ADD: "MPCS_RULES_ADD",
    MPCS_RULES_EDIT: "MPCS_RULES_EDIT",
    MPCS_RULES_DELETE: "MPCS_RULES_DELETE",
    MPCS_RULES_SAVE: "MPCS_RULES_SAVE",

    // Templates
    MPCS_TEMPLATE_CREATE: "MPCS_TEMPLATE_CREATE",
    MPCS_TEMPLATE_SAVE: "MPCS_TEMPLATE_SAVE",
    MPCS_TEMPLATE_DUPLICATE: "MPCS_TEMPLATE_DUPLICATE",
    MPCS_TEMPLATE_DELETE: "MPCS_TEMPLATE_DELETE",
    MPCS_TEMPLATE_OPEN_BUILDER: "MPCS_TEMPLATE_OPEN_BUILDER",

    // Generate
    MPCS_GENERATE_SELECT_TEMPLATE: "MPCS_GENERATE_SELECT_TEMPLATE",
    MPCS_GENERATE_SELECT_PHONE_A: "MPCS_GENERATE_SELECT_PHONE_A",
    MPCS_GENERATE_SELECT_PHONE_B: "MPCS_GENERATE_SELECT_PHONE_B",
    MPCS_GENERATE_PREVIEW: "MPCS_GENERATE_PREVIEW",
    MPCS_GENERATE_SAVE_PROJECT: "MPCS_GENERATE_SAVE_PROJECT",

    // Projects
    MPCS_PROJECTS_OPEN: "MPCS_PROJECTS_OPEN",
    MPCS_PROJECTS_DELETE: "MPCS_PROJECTS_DELETE",
    MPCS_PROJECTS_EXPORT: "MPCS_PROJECTS_EXPORT",
    MPCS_PROJECTS_EDIT: "MPCS_PROJECTS_EDIT",
    MPCS_PROJECTS_RENAME: "MPCS_PROJECTS_RENAME",

    // Settings
    MPCS_SETTINGS_THEME_TOGGLE: "MPCS_SETTINGS_THEME_TOGGLE",
    MPCS_SETTINGS_RULES_ADMIN: "MPCS_SETTINGS_RULES_ADMIN",
    MPCS_SETTINGS_DATA_IMPORT: "MPCS_SETTINGS_DATA_IMPORT",
    MPCS_SETTINGS_DATA_EXPORT: "MPCS_SETTINGS_DATA_EXPORT",
    MPCS_SETTINGS_SAVE_ASPECT_RATIO: "MPCS_SETTINGS_SAVE_ASPECT_RATIO",

    // Aspect Ratio
    MPCS_GENERATE_ASPECT_RATIO_CHANGE: "MPCS_GENERATE_ASPECT_RATIO_CHANGE",
    MPCS_GENERATE_ASPECT_RATIO_TOGGLE_OVERRIDE: "MPCS_GENERATE_ASPECT_RATIO_TOGGLE_OVERRIDE",

    // Phase 2A - Rules
    MPCS_RULES_TYPE_CHANGE: "MPCS_RULES_TYPE_CHANGE",
    MPCS_RULES_ALPHA_MODE_CHANGE: "MPCS_RULES_ALPHA_MODE_CHANGE",
    MPCS_RULES_RANKING_LIST_EDIT: "MPCS_RULES_RANKING_LIST_EDIT",
    MPCS_RULES_RANKING_DIR_CHANGE: "MPCS_RULES_RANKING_DIR_CHANGE",

    // Phase 2A - Phones
    MPCS_PHONES_IMAGE_UPLOAD: "MPCS_PHONES_IMAGE_UPLOAD",
    MPCS_PHONES_IMAGE_REMOVE: "MPCS_PHONES_IMAGE_REMOVE",

    // Phase 2A - Preview
    MPCS_PREVIEW_ZOOM_IN: "MPCS_PREVIEW_ZOOM_IN",
    MPCS_PREVIEW_ZOOM_OUT: "MPCS_PREVIEW_ZOOM_OUT",
    MPCS_PREVIEW_ZOOM_RESET: "MPCS_PREVIEW_ZOOM_RESET",
    MPCS_PREVIEW_FULLSCREEN_TOGGLE: "MPCS_PREVIEW_FULLSCREEN_TOGGLE",

    // Phase 2B Placeholders
    MPCS_PHASE2B_ANIMATIONS_PLACEHOLDER: "MPCS_PHASE2B_ANIMATIONS_PLACEHOLDER",
    MPCS_PHASE2B_AUDIO_PLACEHOLDER: "MPCS_PHASE2B_AUDIO_PLACEHOLDER",
    MPCS_PHASE2B_JSON_PLACEHOLDER: "MPCS_PHASE2B_JSON_PLACEHOLDER",
    MPCS_PHASE2B_MUSIC_PLACEHOLDER: "MPCS_PHASE2B_MUSIC_PLACEHOLDER",
    // Phase 2B - Animations
    MPCS_ANIM_TYPE_CHANGE: "MPCS_ANIM_TYPE_CHANGE",
    MPCS_ANIM_DURATION_CHANGE: "MPCS_ANIM_DURATION_CHANGE",
    MPCS_ANIM_TOGGLE_OVERRIDE: "MPCS_ANIM_TOGGLE_OVERRIDE",

    // Phase 2B - Audio Scoring
    MPCS_AUDIO_TOGGLE: "MPCS_AUDIO_TOGGLE",
    MPCS_AUDIO_VOLUME_CHANGE: "MPCS_AUDIO_VOLUME_CHANGE",
    MPCS_AUDIO_UPLOAD_GOOD: "MPCS_AUDIO_UPLOAD_GOOD",
    MPCS_AUDIO_UPLOAD_BAD: "MPCS_AUDIO_UPLOAD_BAD",
    MPCS_AUDIO_TEST_GOOD: "MPCS_AUDIO_TEST_GOOD",
    MPCS_AUDIO_TEST_BAD: "MPCS_AUDIO_TEST_BAD",

    // Phase 2B - Music
    MPCS_MUSIC_UPLOAD: "MPCS_MUSIC_UPLOAD",
    MPCS_MUSIC_PLAY_PAUSE: "MPCS_MUSIC_PLAY_PAUSE",
    MPCS_MUSIC_VOLUME_CHANGE: "MPCS_MUSIC_VOLUME_CHANGE",
    MPCS_MUSIC_LOOP_TOGGLE: "MPCS_MUSIC_LOOP_TOGGLE",
    MPCS_MUSIC_REMOVE: "MPCS_MUSIC_REMOVE",

    // Phase 2B - JSON Export/Import
    MPCS_PROJECT_EXPORT_JSON: "MPCS_PROJECT_EXPORT_JSON",
    MPCS_PROJECTS_IMPORT_OPEN: "MPCS_PROJECTS_IMPORT_OPEN",
    MPCS_PROJECTS_IMPORT_FILE_PICK: "MPCS_PROJECTS_IMPORT_FILE_PICK",
    MPCS_PROJECTS_IMPORT_DROP: "MPCS_PROJECTS_IMPORT_DROP",
    MPCS_PROJECTS_IMPORT_CONFIRM_DUPLICATE: "MPCS_PROJECTS_IMPORT_CONFIRM_DUPLICATE",
    MPCS_PROJECTS_IMPORT_CONFIRM_OVERWRITE: "MPCS_PROJECTS_IMPORT_CONFIRM_OVERWRITE",
    MPCS_PROJECTS_IMPORT_CANCEL: "MPCS_PROJECTS_IMPORT_CANCEL",
    MPCS_PROJECTS_IMPORT_SUCCESS: "MPCS_PROJECTS_IMPORT_SUCCESS",
    MPCS_PROJECTS_IMPORT_ERROR: "MPCS_PROJECTS_IMPORT_ERROR",

    // UI/UX Improvements Fixes
    MPCS_SETTINGS_APPEARANCE_CHANGE: "MPCS_SETTINGS_APPEARANCE_CHANGE",
    MPCS_SETTINGS_APPEARANCE_SAVE: "MPCS_SETTINGS_APPEARANCE_SAVE",
    MPCS_TEMPLATE_ASPECT_OVERRIDE_TOGGLE: "MPCS_TEMPLATE_ASPECT_OVERRIDE_TOGGLE",
    MPCS_TEMPLATE_ASPECT_OVERRIDE_CHANGE: "MPCS_TEMPLATE_ASPECT_OVERRIDE_CHANGE",
    MPCS_GENERATE_SCENE_SELECT: "MPCS_GENERATE_SCENE_SELECT",
    MPCS_GENERATE_SCENE_TEXT_EDIT: "MPCS_GENERATE_SCENE_TEXT_EDIT",
    MPCS_GENERATE_SCENE_RESET: "MPCS_GENERATE_SCENE_RESET",
    MPCS_GENERATE_SCENE_RESET_ALL: "MPCS_GENERATE_SCENE_RESET_ALL",
    MPCS_SCENE_SELECT: "MPCS_SCENE_SELECT",
    MPCS_SCENE_TOGGLE_ENABLED: "MPCS_SCENE_TOGGLE_ENABLED",
    MPCS_SCENE_DURATION_CHANGE: "MPCS_SCENE_DURATION_CHANGE",
    MPCS_SCENE_TRANSITION_CHANGE: "MPCS_SCENE_TRANSITION_CHANGE",
    MPCS_SCENE_TRANSITION_DURATION_CHANGE: "MPCS_SCENE_TRANSITION_DURATION_CHANGE",
    MPCS_SCENE_TEXT_OVERRIDE_CHANGE: "MPCS_SCENE_TEXT_OVERRIDE_CHANGE",
    MPCS_SCENE_WINNER_OVERRIDE_CHANGE: "MPCS_SCENE_WINNER_OVERRIDE_CHANGE",
    MPCS_SCENE_MEDIA_MODE_CHANGE: "MPCS_SCENE_MEDIA_MODE_CHANGE",
    MPCS_SCENE_MEDIA_UPLOAD_A: "MPCS_SCENE_MEDIA_UPLOAD_A",
    MPCS_SCENE_MEDIA_UPLOAD_B: "MPCS_SCENE_MEDIA_UPLOAD_B",
    MPCS_SCENE_RESET_ONE: "MPCS_SCENE_RESET_ONE",

    // Video Player
    MPCS_PLAYER_PLAY_PAUSE: "MPCS_PLAYER_PLAY_PAUSE",
    MPCS_PLAYER_NEXT: "MPCS_PLAYER_NEXT",
    MPCS_PLAYER_PREV: "MPCS_PLAYER_PREV",
    MPCS_PLAYER_SEEK: "MPCS_PLAYER_SEEK",
    MPCS_PLAYER_SPEED_CHANGE: "MPCS_PLAYER_SPEED_CHANGE",

    // Phase 3: Visual Editor
    MPCS_EDITOR_OPEN: "MPCS_EDITOR_OPEN",
    MPCS_EDITOR_SCENE_OPEN: "MPCS_EDITOR_SCENE_OPEN",
    MPCS_EDITOR_ADD_TEXT: "MPCS_EDITOR_ADD_TEXT",
    MPCS_EDITOR_ADD_IMAGE_PHONE_A: "MPCS_EDITOR_ADD_IMAGE_PHONE_A",
    MPCS_EDITOR_ADD_IMAGE_PHONE_B: "MPCS_EDITOR_ADD_IMAGE_PHONE_B",
    MPCS_EDITOR_ADD_IMAGE_CUSTOM: "MPCS_EDITOR_ADD_IMAGE_CUSTOM",
    MPCS_EDITOR_ADD_BADGE: "MPCS_EDITOR_ADD_BADGE",
    MPCS_EDITOR_ADD_ICON: "MPCS_EDITOR_ADD_ICON",
    MPCS_EDITOR_LAYER_SELECT: "MPCS_EDITOR_LAYER_SELECT",
    MPCS_EDITOR_LAYER_HIDE: "MPCS_EDITOR_LAYER_HIDE",
    MPCS_EDITOR_LAYER_LOCK: "MPCS_EDITOR_LAYER_LOCK",
    MPCS_EDITOR_LAYER_UP: "MPCS_EDITOR_LAYER_UP",
    MPCS_EDITOR_LAYER_DOWN: "MPCS_EDITOR_LAYER_DOWN",
    MPCS_EDITOR_UNDO: "MPCS_EDITOR_UNDO",
    MPCS_EDITOR_REDO: "MPCS_EDITOR_REDO",
    MPCS_EDITOR_SPLIT_H: "MPCS_EDITOR_SPLIT_H",
    MPCS_EDITOR_SPLIT_V: "MPCS_EDITOR_SPLIT_V",
    MPCS_EDITOR_GRID_TOGGLE: "MPCS_EDITOR_GRID_TOGGLE",
    MPCS_EDITOR_SNAP_TOGGLE: "MPCS_EDITOR_SNAP_TOGGLE",
    MPCS_EDITOR_SCENE_DURATION: "MPCS_EDITOR_SCENE_DURATION",
    MPCS_EDITOR_SCENE_TRANSITION: "MPCS_EDITOR_SCENE_TRANSITION",
    MPCS_EDITOR_KENBURNS_TOGGLE: "MPCS_EDITOR_KENBURNS_TOGGLE",
    MPCS_EDITOR_KENBURNS_START: "MPCS_EDITOR_KENBURNS_START",
    MPCS_EDITOR_KENBURNS_END: "MPCS_EDITOR_KENBURNS_END",
    MPCS_EDITOR_AUDIO_UPLOAD: "MPCS_EDITOR_AUDIO_UPLOAD",
    MPCS_EDITOR_AUDIO_TOGGLE: "MPCS_EDITOR_AUDIO_TOGGLE",
    MPCS_EDITOR_AUDIO_VOLUME: "MPCS_EDITOR_AUDIO_VOLUME",

    // Phase 3: Export
    MPCS_EXPORT_OPEN: "MPCS_EXPORT_OPEN",
    MPCS_EXPORT_START: "MPCS_EXPORT_START",
    MPCS_EXPORT_CANCEL: "MPCS_EXPORT_CANCEL",
    MPCS_EXPORT_DONE: "MPCS_EXPORT_DONE",
} as const;

export type ActionId = typeof ACTIONS[keyof typeof ACTIONS];

// Action descriptions for documentation
export const ACTION_DESCRIPTIONS: Record<ActionId, string> = {
    // Navigation
    MPCS_NAV_DASHBOARD: "Navigate to Dashboard",
    MPCS_NAV_PHONES: "Navigate to Phones Management",
    MPCS_NAV_RULES: "Navigate to Rule Map",
    MPCS_NAV_TEMPLATES: "Navigate to Templates",
    MPCS_NAV_GENERATE: "Navigate to Generate Project",
    MPCS_NAV_PROJECTS: "Navigate to Projects",
    MPCS_NAV_SETTINGS: "Navigate to Settings",

    // Dashboard
    MPCS_DASHBOARD_ADD_PHONE: "Quick Action: Add Phone",
    MPCS_DASHBOARD_CREATE_TEMPLATE: "Quick Action: Create Template",
    MPCS_DASHBOARD_GENERATE_PROJECT: "Quick Action: Generate Project",

    // Phones
    MPCS_PHONES_ADD: "Open Add Phone Modal",
    MPCS_PHONES_EDIT: "Open Edit Phone Modal",
    MPCS_PHONES_DELETE: "Open Delete Phone Confirmation",
    MPCS_PHONES_SAVE: "Save Phone Details",
    MPCS_PHONES_SPEC_ADD_ROW: "Add Spec Row to Phone",
    MPCS_PHONES_SPEC_REMOVE_ROW: "Remove Spec Row from Phone",

    // Rules
    MPCS_RULES_ADD: "Open Add Rule Modal",
    MPCS_RULES_EDIT: "Open Edit Rule Modal",
    MPCS_RULES_DELETE: "Open Delete Rule Confirmation",
    MPCS_RULES_SAVE: "Save Rule Changes",

    // Templates
    MPCS_TEMPLATE_CREATE: "Open Create Template Modal",
    MPCS_TEMPLATE_SAVE: "Save Template Changes",
    MPCS_TEMPLATE_DUPLICATE: "Duplicate Selected Template",
    MPCS_TEMPLATE_DELETE: "Delete Selected Template",
    MPCS_TEMPLATE_OPEN_BUILDER: "Navigate to Template Builder",

    // Generate
    MPCS_GENERATE_SELECT_TEMPLATE: "Select Template for Project",
    MPCS_GENERATE_SELECT_PHONE_A: "Select Phone A for Comparison",
    MPCS_GENERATE_SELECT_PHONE_B: "Select Phone B for Comparison",
    MPCS_GENERATE_PREVIEW: "Generate Project Preview",
    MPCS_GENERATE_SAVE_PROJECT: "Save Generated Project",

    // Projects
    MPCS_PROJECTS_OPEN: "Open Project Details",
    MPCS_PROJECTS_DELETE: "Delete Project",
    MPCS_PROJECTS_EXPORT: "Export Project (Phase 3)",
    MPCS_PROJECTS_EDIT: "Edit Project (Phase 3)",
    MPCS_PROJECTS_RENAME: "Rename Project",

    // Settings
    MPCS_SETTINGS_THEME_TOGGLE: "Toggle Theme (Mock)",
    MPCS_SETTINGS_RULES_ADMIN: "Navigate to Rule Admin",
    MPCS_SETTINGS_DATA_IMPORT: "Import Data (Phase 2)",
    MPCS_SETTINGS_DATA_EXPORT: "Export Data (Phase 2)",
    MPCS_SETTINGS_SAVE_ASPECT_RATIO: "Save Default Aspect Ratio",

    // Aspect Ratio
    MPCS_GENERATE_ASPECT_RATIO_CHANGE: "Change Preview Aspect Ratio",
    MPCS_GENERATE_ASPECT_RATIO_TOGGLE_OVERRIDE: "Toggle Project Aspect Ratio Override",

    // Phase 2A - Rules
    MPCS_RULES_TYPE_CHANGE: "Change Rule Comparison Type",
    MPCS_RULES_ALPHA_MODE_CHANGE: "Change Alphanumeric Mode",
    MPCS_RULES_RANKING_LIST_EDIT: "Edit Ranking Hierarchy",
    MPCS_RULES_RANKING_DIR_CHANGE: "Change Ranking Direction",

    // Phase 2A - Phones
    MPCS_PHONES_IMAGE_UPLOAD: "Upload Phone Image",
    MPCS_PHONES_IMAGE_REMOVE: "Remove Phone Image",

    // Phase 2A - Preview
    MPCS_PREVIEW_ZOOM_IN: "Preview Zoom In",
    MPCS_PREVIEW_ZOOM_OUT: "Preview Zoom Out",
    MPCS_PREVIEW_ZOOM_RESET: "Preview Zoom Reset",
    MPCS_PREVIEW_FULLSCREEN_TOGGLE: "Toggle Preview Fullscreen",

    // Phase 2B Placeholders
    MPCS_PHASE2B_ANIMATIONS_PLACEHOLDER: "Toggle Animations (Phase 2B)",
    MPCS_PHASE2B_AUDIO_PLACEHOLDER: "Toggle Audio Scoring (Phase 2B)",
    MPCS_PHASE2B_JSON_PLACEHOLDER: "Export/Import JSON (Phase 2B)",
    MPCS_PHASE2B_MUSIC_PLACEHOLDER: "Select Music (Phase 2B)",

    // Phase 2B - Animations
    MPCS_ANIM_TYPE_CHANGE: "Change Animation Type",
    MPCS_ANIM_DURATION_CHANGE: "Adjust Animation Duration",
    MPCS_ANIM_TOGGLE_OVERRIDE: "Toggle Animation Override",

    // Phase 2B - Audio Scoring
    MPCS_AUDIO_TOGGLE: "Toggle Preview Audio Scoring",
    MPCS_AUDIO_VOLUME_CHANGE: "Change Audio Volume",
    MPCS_AUDIO_UPLOAD_GOOD: "Upload Good SFX",
    MPCS_AUDIO_UPLOAD_BAD: "Upload Bad SFX",
    MPCS_AUDIO_TEST_GOOD: "Test Good SFX",
    MPCS_AUDIO_TEST_BAD: "Test Bad SFX",

    // Phase 2B - Music
    MPCS_MUSIC_UPLOAD: "Upload Background Music",
    MPCS_MUSIC_PLAY_PAUSE: "Toggle Music Playback",
    MPCS_MUSIC_VOLUME_CHANGE: "Change Music Volume",
    MPCS_MUSIC_LOOP_TOGGLE: "Toggle Music Loop",
    MPCS_MUSIC_REMOVE: "Remove Background Music",

    // Phase 2B - JSON Export/Import
    MPCS_PROJECT_EXPORT_JSON: "Export Project to JSON",
    MPCS_PROJECTS_IMPORT_OPEN: "Open Import Project Modal",
    MPCS_PROJECTS_IMPORT_DROP: "Drop File to Import",
    MPCS_PROJECTS_IMPORT_FILE_PICK: "Pick File for Import",
    MPCS_PROJECTS_IMPORT_CONFIRM_DUPLICATE: "Confirm Import as Duplicate",
    MPCS_PROJECTS_IMPORT_CONFIRM_OVERWRITE: "Confirm Import as Overwrite",
    MPCS_PROJECTS_IMPORT_CANCEL: "Cancel Project Import",
    MPCS_PROJECTS_IMPORT_SUCCESS: "Import Successful",
    MPCS_PROJECTS_IMPORT_ERROR: "Import Failed",

    // UI/UX Improvements Fixes
    MPCS_SETTINGS_APPEARANCE_CHANGE: "Change Appearance Setting",
    MPCS_SETTINGS_APPEARANCE_SAVE: "Save Appearance Setting",
    MPCS_TEMPLATE_ASPECT_OVERRIDE_TOGGLE: "Toggle Template Aspect Ratio Override",
    MPCS_TEMPLATE_ASPECT_OVERRIDE_CHANGE: "Change Template Specific Aspect Ratio",
    MPCS_GENERATE_SCENE_SELECT: "Select Scene for Inspection",
    MPCS_GENERATE_SCENE_TEXT_EDIT: "Edit Scene Text Content",
    MPCS_GENERATE_SCENE_RESET: "Reset Scene to Auto-generated Content",
    MPCS_GENERATE_SCENE_RESET_ALL: "Reset All Scenes",
    MPCS_SCENE_SELECT: "Select Scene",
    MPCS_SCENE_TOGGLE_ENABLED: "Toggle Scene Enabled",
    MPCS_SCENE_DURATION_CHANGE: "Change Scene Duration",
    MPCS_SCENE_TRANSITION_CHANGE: "Change Scene Transition",
    MPCS_SCENE_TRANSITION_DURATION_CHANGE: "Change Transition Duration",
    MPCS_SCENE_TEXT_OVERRIDE_CHANGE: "Change Text Override",
    MPCS_SCENE_WINNER_OVERRIDE_CHANGE: "Change Winner Override",
    MPCS_SCENE_MEDIA_MODE_CHANGE: "Change Media Mode",
    MPCS_SCENE_MEDIA_UPLOAD_A: "Upload Media Phone A",
    MPCS_SCENE_MEDIA_UPLOAD_B: "Upload Media Phone B",
    MPCS_SCENE_RESET_ONE: "Reset Single Scene",

    // Video Player
    MPCS_PLAYER_PLAY_PAUSE: "Play or Pause Video Preview",
    MPCS_PLAYER_NEXT: "Advance to Next Scene",
    MPCS_PLAYER_PREV: "Return to Previous Scene",
    MPCS_PLAYER_SEEK: "Seek to Position in Preview",
    MPCS_PLAYER_SPEED_CHANGE: "Change Playback Speed",

    // Phase 3: Visual Editor
    MPCS_EDITOR_OPEN: "Open Visual Editor",
    MPCS_EDITOR_SCENE_OPEN: "Open Scene in Editor",
    MPCS_EDITOR_ADD_TEXT: "Add Text Element",
    MPCS_EDITOR_ADD_IMAGE_PHONE_A: "Add Phone A Image",
    MPCS_EDITOR_ADD_IMAGE_PHONE_B: "Add Phone B Image",
    MPCS_EDITOR_ADD_IMAGE_CUSTOM: "Add Custom Image",
    MPCS_EDITOR_ADD_BADGE: "Add Badge Element",
    MPCS_EDITOR_ADD_ICON: "Add Icon Element",
    MPCS_EDITOR_LAYER_SELECT: "Select Layer",
    MPCS_EDITOR_LAYER_HIDE: "Toggle Layer Visibility",
    MPCS_EDITOR_LAYER_LOCK: "Toggle Layer Lock",
    MPCS_EDITOR_LAYER_UP: "Move Layer Up",
    MPCS_EDITOR_LAYER_DOWN: "Move Layer Down",
    MPCS_EDITOR_UNDO: "Undo Action",
    MPCS_EDITOR_REDO: "Redo Action",
    MPCS_EDITOR_SPLIT_H: "Split Element Horizontally",
    MPCS_EDITOR_SPLIT_V: "Split Element Vertically",
    MPCS_EDITOR_GRID_TOGGLE: "Toggle Grid",
    MPCS_EDITOR_SNAP_TOGGLE: "Toggle Snap",
    MPCS_EDITOR_SCENE_DURATION: "Change Scene Duration",
    MPCS_EDITOR_SCENE_TRANSITION: "Change Scene Transition",
    MPCS_EDITOR_KENBURNS_TOGGLE: "Toggle Ken Burns Effect",
    MPCS_EDITOR_KENBURNS_START: "Set Ken Burns Start",
    MPCS_EDITOR_KENBURNS_END: "Set Ken Burns End",
    MPCS_EDITOR_AUDIO_UPLOAD: "Upload Project Audio",
    MPCS_EDITOR_AUDIO_TOGGLE: "Toggle Project Audio",
    MPCS_EDITOR_AUDIO_VOLUME: "Change Project Audio Volume",

    // Phase 3: Export
    MPCS_EXPORT_OPEN: "Open Export Modal",
    MPCS_EXPORT_START: "Start Video Export",
    MPCS_EXPORT_CANCEL: "Cancel Video Export",
    MPCS_EXPORT_DONE: "Video Export Completed",
};
